### ISSUE TITLE
Windows XP can't be installed for me

### ISSUE THREAD

**Issue by rwilming** [OBattler/86Box#53]
Everytime I try to run the Windows XP Setup from CD boot I get this no matter If I use the 440FX or 430VX
![image](https://cloud.githubusercontent.com/assets/24677730/21352448/c6059b82-c6c1-11e6-92cf-7122bde8d4d1.png)
and that is the BSOD I get when I try to run the Setup

**Comment by rwilming** [comment]
It's the same with 2000 but I can install the Windows XP Beta

**Comment by TC1995** [comment]
Just don't use the 440fx machine.

**Comment by rwilming** [comment]
It also doesn't work on the 430 VX

**Comment by rwilming** [comment]
![image](https://cloud.githubusercontent.com/assets/24677730/21361723/89d3f874-c6e5-11e6-87ed-7f733975d091.png)
This is what happens when I disable the External Cache, It doesn't get any further

**Comment by MoochMcGee** [comment]
Use the Epox P55-VA, the two systems you're describing are known to be
bugged.

**Comment by rwilming** [comment]
![image](https://cloud.githubusercontent.com/assets/24677730/21367103/18a7b0f6-c6fd-11e6-8bdc-29d1ebfd8794.png)
This is the first try with the Epox P55-VA and It already got stuch at this

**Comment by MoochMcGee** [comment]
I dunno what to tell you then, because it works for us.

**Comment by rwilming** [comment]
I think it could be that the Intel Core i5-4690 that is in my PC is causing the problem

**Comment by rwilming** [comment]
I'm gonna try it on my Laptop tomorrow and see if it works on that

**Comment by rwilming** [comment]
nope my Laptop just get's the same result like I got on the Epox P55-A on the 440FX now I'M gonna try the Epox

**Comment by rwilming** [comment]
My Laptop does the same as my host on the Epox

**Comment by MoochMcGee** [comment]
It works for everybody else. Try the official romset on the IRC.

**Comment by rwilming** [comment]
that also didn't fix it

**Comment by MoochMcGee** [comment]
Well, I don't know then, because it works for literally every single dev.

**Comment by rwilming** [comment]
I just got the new version and it seems that my prblems fixed now atleast with 2000 and I can set the RAM of the 440FX to 1024 MB now without it crashing

**Comment by rwilming** [comment]
![image](https://cloud.githubusercontent.com/assets/24677730/21464185/13ecb900-c976-11e6-86af-bc9762802191.png)
the new version fixed it

**Comment by W9JYD** [comment]
Still doesn't work, Latest version. An "it works for me" is UNHELPFUL.

**Comment by cold-brewed** [comment]
@W9JYD This is a very old issue. If this is still a problem for you, could you open a new issue to troubleshoot? As far as I'm aware there are not currently any issues preventing XP installation.
